name: streamlit-refactored
channels:
  - conda-forge
dependencies:
  # System
  - git
  - nodejs=20
  - npm
  
  # Core Python (Install via Conda for stability)
  - python=3.10
  - pyyaml
  - requests
  - streamlit
  
  # Pip-only packages
  - pip
  - pip:
    - python-dotenv
    - google-genai
