name: streamlit-refactored
channels:
  - conda-forge
dependencies:
  - git
  - nodejs=20
  - npm
  - python=3.10
  - pip
  - pip:
    - streamlit
    - requests
    - PyYAML
    - python-dotenv
    - google-genai
